name: 'Docker Hub Upstream'
description: 'Monitor updates to Docker images and automatically perform a commit and release on your project.'
author: 'Samuel Fontebasso'
branding:
  icon: 'cloud-rain'
  color: 'gray-dark'
inputs:
  token:
    required: true
    description: 'The GitHub token to use for the commit.'
  image:
    required: true
    description: 'The name of the docker image.'
    default: 'null'
  tag:
    required: true
    description: 'The docker image tag to monitor.'
    default: 'latest'
runs:
  using: 'node16'
  main: 'dist/index.js'
